version: '3.9'
services:
  database:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tinyurl_DB
    networks:
      - tiny-url-network
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - tiny-url-network
  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    depends_on:
      - prometheus
    networks:
      - tiny-url-network
  tinyurl:
    image: aravindssr/arav:tinyurl.12.0
    ports:
      - "8082:8082"
    depends_on:
      - database
      - prometheus
      - grafana
    networks:
      - tiny-url-network

networks:
   tiny-url-network: